"""Internal types shim for openai package compatibility in tests."""
# Provide minimal aliases used by the codebase
from typing import TypeVar, Any, Optional
from pydantic import BaseModel

T = TypeVar('T')

def Omit(type_obj, keys):
    return type_obj


# Use pydantic BaseModel so schemas can be generated by pydantic
class Body(BaseModel):
    content: Optional[Any] = None


class Query(BaseModel):
    query: Optional[str] = None


class Request(BaseModel):
    data: Optional[Any] = None


class Response(BaseModel):
    data: Optional[Any] = None


__all__ = ['Omit', 'T', 'Body', 'Query', 'Request', 'Response']
